const $=s=>document.querySelector(s);const code=$('#code'),result=$('#result'),trace=$('#trace'),caps=$('#caps'),empty=$('#emptyCaps'),next=$('#next'),proof=$('#proof'),proofGrid=$('#proofGrid');let step=0,installed=true,instinct=false;
const worlds={B:`# WORLD B · HELD OUT\n\ndef slice_length(data, start, end):\n    return data[start:end]\n\n# expected: preserve boundary semantics`,A:`# WORLD A · INDEPENDENT EXPERIENCE\n\ndef boundary_ok(x, limit):\n    if x < limit:\n        return accept(x)\n    return reject(x)`,C:`# WORLD C · NEXT FRONTIER\n\ndef merge_flags(left, right):\n    if left < right and ready(left):\n        return combine(left, right)\n    return None`};
const addTrace=(icon,text,state='')=>{let d=document.createElement('div');d.className='trace-row';d.innerHTML=`<span class="${state}">${icon}</span><b>${text}</b><small>${state==='ok'?'VERIFIED':''}</small>`;trace.appendChild(d)};
const verdict=(kind,text)=>{result.className='result '+kind;result.innerHTML=`<span class="result-icon">${kind==='pass'?'✓':kind==='fail'?'×':'○'}</span><div><small>EXTERNAL VERDICT</small><strong>${text}</strong></div>`};
const capHTML=()=>{empty.style.display='none';caps.innerHTML=`<div class="cap ${instinct?'instinct':''}" id="c17"><div class="cap-top"><span class="cap-id">C17</span><span class="cap-name">Boundary Inclusion</span><span class="cap-status">${instinct?'INSTINCT':'ACTIVE'}</span></div><p>&lt; → &lt;= · scoped · attested<br>dependencies: none · provenance locked</p><button id="toggle">${installed?'UNINSTALL':'INSTALL'}</button>${installed&&!instinct?'<button id="compile">MAKE INSTINCT</button>':''}</div>${step>=6?`<div class="cap"><div class="cap-top"><span class="cap-id">C18</span><span class="cap-name">Guard Disjunction</span><span class="cap-status">DISCOVERED</span></div><p>and → or · requires C17 lineage<br>discoverable only after C17</p></div>`:''}`;$('#capCount').textContent=(step>=6?'2':'1')+' LEARNED';let t=$('#toggle');if(t)t.onclick=()=>{installed=!installed;toast(installed?'C17 INSTALLED':'C17 UNINSTALLED');if(step>=4){verdict(installed?'pass':'fail',installed?'PASS · C17 INVOKED':'FAIL · CAPABILITY ABSENT')}capHTML()};let c=$('#compile');if(c)c.onclick=()=>{instinct=true;toast('MACHINE INSTINCT READY');capHTML()}};
const toast=t=>{let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1500)};
const setWorld=(name)=>{$('#worldBadge').textContent='WORLD '+name;code.textContent=worlds[name]};
const steps=[
()=>{setWorld('B');trace.innerHTML='';verdict('fail','FAIL · BASELINE');addTrace('→','Attempt held-out task','info');addTrace('×','No applicable capability','bad');next.innerHTML='SHOW EXPERIENCE A →';},
()=>{setWorld('A');verdict('fail','FAIL · RESIDUAL');trace.innerHTML='';addTrace('→','Attempt','info');addTrace('×','Residual: boundary mismatch','bad');addTrace('…','Testing closure(A₀)','info');next.innerHTML='LEARN FROM FAILURE →';},
()=>{addTrace('×','Not expressible in existing closure','bad');addTrace('+','Construct candidate: < → <=','info');addTrace('✓','External tests 14 / 14','ok');addTrace('✓','Protected regressions 9 / 9','ok');addTrace('✓','Scope attested','ok');installed=true;capHTML();verdict('pass','CAPABILITY C17 VERIFIED');next.innerHTML='RETURN TO WORLD B →';},
()=>{setWorld('B');trace.innerHTML='';addTrace('→','Fresh context','info');addTrace('✓','C17 applicability verified','ok');addTrace('→','Invoke C17','info');verdict('pass','PASS · C17 INVOKED');next.innerHTML='PROVE CAUSALITY →';},
()=>{proof.classList.add('visible');$('#proofTitle').textContent='The capability is the cause.';proofGrid.innerHTML=`<div class="proof-cell fail"><b>BASE</b><span>FAIL</span></div><div class="proof-cell pass"><b>+ C17</b><span>PASS</span></div><div class="proof-cell fail"><b>− C17</b><span>FAIL</span></div><div class="proof-cell pass"><b>REINSTALL</b><span>PASS</span></div>`;toast('0 → 1 → 0 → 1');next.innerHTML='TEST WHAT IT CAN LEARN →';},
()=>{setWorld('C');trace.innerHTML='';addTrace('…','Search with A₀','info');addTrace('×','No new operator discoverable in budget','bad');addTrace('+','Restore C17','info');addTrace('…','Same discovery procedure','info');next.innerHTML='CONTINUE SAME SEARCH →';},
()=>{addTrace('!','New residual exposed','info');addTrace('+','C18: and → or','info');addTrace('✓','C18 externally verified','ok');capHTML();verdict('pass','PASS · C17 + C18');$('#headline').innerHTML='Learning changed<br><em>what it could learn next.</em>';$('#subhead').textContent='C18 was outside the original discoverable frontier. C17 made it reachable under the same frozen search budget.';next.innerHTML='MAKE IT INSTINCT →';},
()=>{instinct=true;capHTML();trace.innerHTML='';addTrace('✓','Explicit capability retained','ok');addTrace('→','Compile verified realization','info');addTrace('✓','Fresh reload survives','ok');addTrace('✓','Original experience not required','ok');$('#headline').innerHTML='Intelligence,<br><em>with provenance.</em>';$('#subhead').textContent='Discover. Verify. Install. Invoke. Compile. Revise. Revoke. And let verified development reshape the next frontier.';next.innerHTML='DEMO COMPLETE ↻';proof.classList.add('visible');$('#proofTitle').textContent='LOGOS · OS for Verified Intelligence';proofGrid.innerHTML=`<div class="proof-cell pass"><b>CAPABILITY</b><span>PORTABLE</span></div><div class="proof-cell pass"><b>INVOCATION</b><span>VERIFIED</span></div><div class="proof-cell pass"><b>INSTINCT</b><span>COMPILED</span></div><div class="proof-cell pass"><b>DEVELOPMENT</b><span>COMPOUNDS</span></div>`;}
];
function render(){if(step>=steps.length){reset();return}steps[step]();step++;$('#stepLabel').textContent=`STEP ${step} / ${steps.length}`}
function reset(){step=0;installed=true;instinct=false;caps.innerHTML='';empty.style.display='block';$('#capCount').textContent='0 LEARNED';trace.innerHTML='';proof.classList.remove('visible');$('#headline').innerHTML='Same model.<br><em>Different mind.</em>';$('#subhead').textContent='Watch verified experience become an installable capability — then change what the system can discover next.';next.innerHTML='BEGIN DEMO <span>→</span>';setWorld('B');verdict('','NOT RUN');$('#stepLabel').textContent='STEP 0 / 8'}
next.onclick=render;$('#reset').onclick=reset;reset();