import CLC.Behavior

namespace CLC

/-- A closed transport loop is continuation-neutral when it leaves no
    future-exposable protected residual. -/
def ContinuationNeutral
    {A : Form}
    (ell : VerifiedTransport A A) : Prop :=
  ∀ x : A.State, ContinuationSafe A (ell.mapState x) x

/-- Pointwise residual predicate for a particular future probe. -/
def HasResidualAt
    {A : Form}
    (ell : VerifiedTransport A A)
    (x : A.State)
    (B : Form)
    (c : VerifiedTransport A B)
    (p : ProtectedTest B) : Prop :=
  B.eval (c.mapState (ell.mapState x)) p.1 ≠
  B.eval (c.mapState x) p.1

theorem continuationNeutral_iff_noResidual
    {A : Form}
    (ell : VerifiedTransport A A) :
    ContinuationNeutral ell ↔
      ∀ (x : A.State) (B : Form)
        (c : VerifiedTransport A B)
        (p : ProtectedTest B),
        ¬ HasResidualAt ell x B c p := by
  constructor
  · intro h x B c p hres
    exact hres (h x B c p)
  · intro h x B c p
    by_contra hneq
    exact h x B c p hneq

/-- a : A→B and r : B→A are behavioral inverses when each round trip
    is continuation-neutral. -/
structure BehavioralInverse
    {A B : Form}
    (a : VerifiedTransport A B)
    (r : VerifiedTransport B A) : Prop where
  left : ∀ x : A.State,
    ContinuationSafe A (r.mapState (a.mapState x)) x
  right : ∀ y : B.State,
    ContinuationSafe B (a.mapState (r.mapState y)) y

theorem behavioralInverse_left
    {A B : Form}
    {a : VerifiedTransport A B}
    {r : VerifiedTransport B A}
    (h : BehavioralInverse a r) :
    behaviorMap r ∘ behaviorMap a = id := by
  funext q
  refine Quotient.inductionOn' q ?_
  intro x
  apply Quotient.sound
  exact h.left x

theorem behavioralInverse_right
    {A B : Form}
    {a : VerifiedTransport A B}
    {r : VerifiedTransport B A}
    (h : BehavioralInverse a r) :
    behaviorMap a ∘ behaviorMap r = id := by
  funext q
  refine Quotient.inductionOn' q ?_
  intro y
  apply Quotient.sound
  exact h.right y

/-- The quotient-level equivalence generated by behavioral inverses. -/
def behaviorEquiv
    {A B : Form}
    (a : VerifiedTransport A B)
    (r : VerifiedTransport B A)
    (h : BehavioralInverse a r) :
    Behavior A ≃ Behavior B where
  toFun := behaviorMap a
  invFun := behaviorMap r
  left_inv := by
    intro q
    have hf := congrFun (behavioralInverse_left h) q
    exact hf
  right_inv := by
    intro q
    have hf := congrFun (behavioralInverse_right h) q
    exact hf

end CLC
